Rectifybridge
Switcheo/zilswap-webapp pull request #117
Opened 2021-09-03 07:03 UTC by wasim162010

Modified the target branch to the staging.

2021-09-13 06:42 UTC, stevenkhong commented
closed as duplicate of #116

2021-09-14 06:24 UTC, stevenkhong requested changes

2021-09-14 06:24 UTC, stevenkhong commented on package.json
> +    "web3modal": "git://github.com/bolt-global/web3modal.git#build/add-boltx-wallet",
can we inject bolt-x into the web3modal instead of forking?

2021-09-14 06:24 UTC, stevenkhong commented on src/app/views/main/Bridge/Bridge.tsx
> +      console.log(error)
We should handle the error properly instead of ignoring the error like this. Existing legitimate errors will be ignored if we catch and ignore.

2021-09-14 06:24 UTC, stevenkhong commented on src/app/layouts/WalletDialog/components/ConnectWalletBoltX/ConnectWalletBoltX.tsx
> +      console.log(boltX);
Please remove debug log, or use the built-in logging mechanism `logger`

2021-09-16 04:35 UTC, wasim162010 commented on package.json
> +    "web3modal": "git://github.com/bolt-global/web3modal.git#build/add-boltx-wallet",
Taken care of it.

2021-09-16 04:36 UTC, wasim162010 commented on src/app/views/main/Bridge/Bridge.tsx
> +      console.log(error)
Code changes have been made so this comment can be considered as acknowledged.

2021-09-16 04:38 UTC, wasim162010 commented
Made changes in the code to incorporate Steven's comment.

2021-09-28 14:18 UTC, merged