Staging
Switcheo/zilswap-webapp pull request #26
Opened 2021-05-11 14:37 UTC by whenafirestartstoburn

2021-05-14 05:52 UTC, RavenXce approved these changes

2021-05-14 07:54 UTC, RavenXce requested changes

2021-05-14 07:54 UTC, RavenXce commented on config-overrides.js
> +  config.module.exprContextCritical = false;
Are we able to avoid this?

2021-05-14 07:56 UTC, whenafirestartstoburn commented on config-overrides.js
> +  config.module.exprContextCritical = false;
the only thing this does is supressing warnings about "the request of a dependency is an expression" from external libraries:

2021-05-14 07:57 UTC, whenafirestartstoburn commented on config-overrides.js
> +  config.module.exprContextCritical = false;
those warnings are treated as errors on dpeloyment, cause CI=true is set by circleci

2021-05-14 07:58 UTC, whenafirestartstoburn commented on config-overrides.js
> +  config.module.exprContextCritical = false;
for now I did not find a way to avoid them in Zeeves library... can we accept this as a temporary solution? you should not miss anything important cause of that, only these warnings

2021-05-19 20:54 UTC, whenafirestartstoburn commented on config-overrides.js
> +  config.module.exprContextCritical = false;
@RavenXce okay, we finally found a way to remove those warnings ;) using new zeeves sdk version now

2021-05-31 06:36 UTC, merged